feat: improve version handling
CircleCI-Public/gcp-cli-orb pull request #51
Opened 2022-10-22 05:23 UTC by EricRibeiro

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Closes:

- #49 
- #46 
- #45 
- #19

### Description

This PR changes the default CLI version to `latest`. Users can follow the existing process of specifying it via the `version` parameter if they wish to install a custom version.

It also adds several tests for different platforms, including Alpine. The latter is now officially supported once the user installs the necessary dependencies.

2022-10-24 19:14 UTC, Jaryt commented on src/commands/install.yml
> +        ORB_VAL_VERSION: << parameters.version >>
Maybe no_output_timeout belongs for this one, but keep `when` for the next?

2022-10-24 19:23 UTC, EricRibeiro commented on src/commands/install.yml
> +        ORB_VAL_VERSION: << parameters.version >>
> keep when for the next?

The next step? If so, I don't see why we would need another step in this command.

2022-10-24 19:29 UTC, Jaryt requested changes

2022-10-24 19:29 UTC, Jaryt commented on src/commands/install.yml
> +        ORB_VAL_VERSION: << parameters.version >>
Maybe `when` doesn't exactly make sense in this context then.

2022-10-25 17:46 UTC, Jaryt approved these changes
Lookin good!

2022-10-25 17:51 UTC, merged